apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: dev
  project: default
  source:
    chart: spartapp
    helm:
    repoURL: https://ehienabs.github.io/spartapp
    targetRevision: 0.1.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true